version: '3'

vars:
  GO_MODULE: github.com/twipi/twipi

includes:
  proto:
    taskfile: proto/Taskfile.yml
    dir: proto

tasks:
  default:
    deps: [proto:compile, build-config]

  build-config:
    watch: true
    sources:
      - twid.cfg.nix
    generates:
      - twid.json
    cmds:
      - nix eval --json -f ./twid.cfg.nix > twid.json
