version: '3'

vars:
  GO_MODULE: github.com/twipi/twipi

includes:
  proto:
    taskfile: proto/Taskfile.yml
    dir: proto

tasks:
  default:
    deps: [proto:compile, sqlc, build-config]

  sqlc:
    cmds:
      - sqlc generate

  build-config:
    watch: true
    sources:
      - twid.cfg.nix
    generates:
      - twid.json
    cmds:
      - nix eval --json -f ./twid.cfg.nix > twid.json

  wsbridge-client:
    vars:
      YOUR_NUMBERS: +19876543210
      WSBRIDGE_URL: ws://localhost:8080/sms/ws
    cmds:
      - go run ./cmd/wsbridge-client -v -u {{shellQuote .WSBRIDGE_URL}} {{.YOUR_NUMBERS}}
