version: '3'

vars:
  GO_MODULE: github.com/twipi/twipi
  TWID_PORT: 8080
  TWID_DISCORD_PORT: 8090

includes:
  proto:
    taskfile: proto/Taskfile.yml
    dir: proto

tasks:
  dev:
    deps: [generate]
    cmds:
      - go run ./cmd/twid -vvv -c ./twid.json

  generate:
    deps:
      - proto:compile
      - sqlc
      - build-config

  sqlc:
    cmds:
      - sqlc generate

  build-config:
    watch: true
    sources:
      - twid.cfg.nix
    generates:
      - twid.json
    env:
      TWID_PORT: "{{.TWID_PORT}}"
      TWID_DISCORD_PORT: "{{.TWID_DISCORD_PORT}}"
    cmds:
      - |
        nix-instantiate \
          --eval --strict --json \
          --argstr port {{shellQuote .TWID_PORT}} \
          --argstr discordPort {{shellQuote .TWID_DISCORD_PORT}} \
          ./twid.cfg.nix > twid.json

  wsbridge-client:
    vars:
      YOUR_NUMBERS: +19876543210
      WSBRIDGE_URL: ws://localhost:8080/sms/ws
    cmds:
      - go run ./cmd/wsbridge-client -u {{shellQuote .WSBRIDGE_URL}} {{.YOUR_NUMBERS}}
