version: '3'

includes:
  proto:
    taskfile: proto/Taskfile.yml
    dir: proto
    env:
      GO_MODULE: github.com/twipi/twipi

tasks:
  dev:
    deps: [generate]
    requires:
      vars: [TWID_CONFIG]
    cmds:
      - go run ./cmd/twid -vvv -c "${TWID_CONFIG}"

  generate:
    deps:
      - proto:compile
      - sqlc

  sqlc:
    sources:
      - sqlc.json
      - "**/*.sql"
    cmds:
      - sqlc generate
